name: phoci
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pyg
  - pandas
  - matplotlib
  - notebook
